"""
Domain Models for Daily-Bot
Using Pydantic for validation and serialization
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from src.domain.enums import (
    Category,
    ContentStatus,
    Difficulty,
    ExecutionStatus,
    ReportType,
    ScheduleStatus,
)


class ContentRecord(BaseModel):
    """Represents a generated content record"""

    id: int | None = None
    title: str = Field(..., description="Content title")
    category: Category = Field(..., description="Content category")
    difficulty: Difficulty = Field(Difficulty.INTERMEDIATE, description="Difficulty level")
    summary: str = Field(..., description="Short summary for Slack")
    content: str = Field(..., description="Full content for Notion")
    tags: list[str] = Field(default_factory=list, description="Content tags")
    notion_page_id: str | None = Field(None, description="Notion page ID")
    notion_url: str | None = Field(None, description="Notion page URL")
    slack_ts: str | None = Field(None, description="Slack message timestamp")
    author: str = Field(..., description="Author name")
    status: ContentStatus = Field(ContentStatus.DRAFT, description="Content status")
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime | None = None

    model_config = ConfigDict(use_enum_values=True)


class Schedule(BaseModel):
    """Represents a schedule configuration"""

    id: int | None = None
    time: str = Field(..., description="Schedule time (HH:MM)")
    status: ScheduleStatus = Field(ScheduleStatus.ACTIVE)
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime | None = None

    model_config = ConfigDict(use_enum_values=True)


class ExecutionLog(BaseModel):
    """Represents an execution log entry"""

    id: int | None = None
    schedule_id: int | None = None
    content_id: int | None = None
    status: ExecutionStatus = Field(ExecutionStatus.PENDING)
    attempt_count: int = Field(0, description="Number of attempts")
    error_message: str | None = None
    started_at: datetime = Field(default_factory=datetime.now)
    completed_at: datetime | None = None
    duration_ms: int | None = Field(None, description="Execution duration in milliseconds")

    model_config = ConfigDict(use_enum_values=True)


class TopicRequest(BaseModel):
    """Represents a user-requested topic"""

    id: int | None = None
    topic: str = Field(..., description="Requested topic")
    requested_by: str = Field(..., description="Requester name or ID")
    is_processed: bool = Field(False, description="Whether the topic has been processed")
    content_id: int | None = Field(None, description="Generated content ID if processed")
    created_at: datetime = Field(default_factory=datetime.now)
    processed_at: datetime | None = None

    model_config = ConfigDict(use_enum_values=True)


class ReportData(BaseModel):
    """Represents report data"""

    report_type: ReportType
    period_start: datetime
    period_end: datetime
    total_count: int = 0
    success_count: int = 0
    failed_count: int = 0
    retry_count: int = 0
    category_distribution: dict[str, int] = Field(default_factory=dict)
    uncovered_categories: list[str] = Field(default_factory=list)
    avg_duration_ms: float | None = Field(None, description="Average execution duration")
    min_duration_ms: int | None = Field(None, description="Minimum execution duration")
    max_duration_ms: int | None = Field(None, description="Maximum execution duration")
    generated_at: datetime = Field(default_factory=datetime.now)

    model_config = ConfigDict(use_enum_values=True)


class SlackMessage(BaseModel):
    """Represents a Slack message to send"""

    channel: str
    text: str
    blocks: list[dict[str, Any]] | None = None
    thread_ts: str | None = None


class NotionPage(BaseModel):
    """Represents a Notion page to create"""

    database_id: str
    title: str
    category: str
    difficulty: str
    tags: list[str]
    content: str
    summary: str
    author: str


class GeneratedContent(BaseModel):
    """Represents content generated by Claude Code"""

    title: str
    category: Category
    difficulty: Difficulty
    summary: str
    content: str = ""
    tags: list[str] = Field(default_factory=list)

    model_config = ConfigDict(use_enum_values=True)


class BotStatus(BaseModel):
    """Represents current bot status"""

    is_running: bool = True
    is_paused: bool = False
    active_schedules: list[str] = Field(default_factory=list)
    next_execution: datetime | None = None
    total_generated: int = 0
    last_execution: datetime | None = None
    last_error: str | None = None
    uptime_seconds: int = 0
