"""
Domain Models for Daily-Bot
Using Pydantic for validation and serialization
"""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, ConfigDict

from src.domain.enums import (
    Category,
    Difficulty,
    ExecutionStatus,
    ScheduleStatus,
    ContentStatus,
    ReportType,
)


class ContentRecord(BaseModel):
    """Represents a generated content record"""
    
    id: Optional[int] = None
    title: str = Field(..., description="Content title")
    category: Category = Field(..., description="Content category")
    difficulty: Difficulty = Field(Difficulty.INTERMEDIATE, description="Difficulty level")
    summary: str = Field(..., description="Short summary for Slack")
    content: str = Field(..., description="Full content for Notion")
    tags: List[str] = Field(default_factory=list, description="Content tags")
    notion_page_id: Optional[str] = Field(None, description="Notion page ID")
    notion_url: Optional[str] = Field(None, description="Notion page URL")
    slack_ts: Optional[str] = Field(None, description="Slack message timestamp")
    author: str = Field(..., description="Author name")
    status: ContentStatus = Field(ContentStatus.DRAFT, description="Content status")
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(use_enum_values=True)


class Schedule(BaseModel):
    """Represents a schedule configuration"""
    
    id: Optional[int] = None
    time: str = Field(..., description="Schedule time (HH:MM)")
    status: ScheduleStatus = Field(ScheduleStatus.ACTIVE)
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(use_enum_values=True)


class ExecutionLog(BaseModel):
    """Represents an execution log entry"""
    
    id: Optional[int] = None
    schedule_id: Optional[int] = None
    content_id: Optional[int] = None
    status: ExecutionStatus = Field(ExecutionStatus.PENDING)
    attempt_count: int = Field(0, description="Number of attempts")
    error_message: Optional[str] = None
    started_at: datetime = Field(default_factory=datetime.now)
    completed_at: Optional[datetime] = None
    duration_ms: Optional[int] = Field(None, description="Execution duration in milliseconds")

    model_config = ConfigDict(use_enum_values=True)


class TopicRequest(BaseModel):
    """Represents a user-requested topic"""
    
    id: Optional[int] = None
    topic: str = Field(..., description="Requested topic")
    requested_by: str = Field(..., description="Requester name or ID")
    is_processed: bool = Field(False, description="Whether the topic has been processed")
    content_id: Optional[int] = Field(None, description="Generated content ID if processed")
    created_at: datetime = Field(default_factory=datetime.now)
    processed_at: Optional[datetime] = None

    model_config = ConfigDict(use_enum_values=True)


class ReportData(BaseModel):
    """Represents report data"""
    
    report_type: ReportType
    period_start: datetime
    period_end: datetime
    total_count: int = 0
    success_count: int = 0
    failed_count: int = 0
    retry_count: int = 0
    category_distribution: dict = Field(default_factory=dict)
    uncovered_categories: List[str] = Field(default_factory=list)
    avg_duration_ms: Optional[float] = Field(None, description="Average execution duration")
    min_duration_ms: Optional[int] = Field(None, description="Minimum execution duration")
    max_duration_ms: Optional[int] = Field(None, description="Maximum execution duration")
    generated_at: datetime = Field(default_factory=datetime.now)

    model_config = ConfigDict(use_enum_values=True)


class SlackMessage(BaseModel):
    """Represents a Slack message to send"""
    
    channel: str
    text: str
    blocks: Optional[List[dict]] = None
    thread_ts: Optional[str] = None
    

class NotionPage(BaseModel):
    """Represents a Notion page to create"""
    
    database_id: str
    title: str
    category: str
    difficulty: str
    tags: List[str]
    content: str
    summary: str
    author: str


class GeneratedContent(BaseModel):
    """Represents content generated by Claude Code"""

    title: str
    category: Category
    difficulty: Difficulty
    summary: str
    content: str = ""
    tags: List[str] = Field(default_factory=list)

    model_config = ConfigDict(use_enum_values=True)


class BotStatus(BaseModel):
    """Represents current bot status"""
    
    is_running: bool = True
    is_paused: bool = False
    active_schedules: List[str] = Field(default_factory=list)
    next_execution: Optional[datetime] = None
    total_generated: int = 0
    last_execution: Optional[datetime] = None
    last_error: Optional[str] = None
    uptime_seconds: int = 0
